### ISSUE TITLE
Connection refused 

### ISSUE THREAD

**Issue by damianoneill** [sndyuk/logback-more-appenders#16]
Hi I have setup a EFK docker stack.  I have tested this works correctly by redirecting docker console output for my spring boot app to fluentd with no issues. 

I have modified the spring boot app logging configuration as follows:

build.gradle
```
            compile 'org.fluentd:fluent-logger:0.3.2'
            compile 'com.sndyuk:logback-more-appenders:1.4.1'
```

fluent.conf
```
<source>
type forward
port 24224
bind 0.0.0.0
</source>

<match *.*>
@type elasticsearch
host elasticsearch
logstash_format true
flush_interval 10s
</match>
```

logback-spring.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <include resource="org/springframework/boot/logging/logback/base.xml"/>
    <appender name="FLUENT" class="ch.qos.logback.more.appenders.DataFluentAppender">
        <remoteHost>localhost</remoteHost>
        <port>24224</port>
    </appender>
    <logger name="com.acme.joc" level="debug" additivity="false">
        <appender-ref ref="CONSOLE"/>
        <appender-ref ref="FLUENT"/>
    </logger>
</configuration>
```

And got the following exception.

console output
```
...
2017-01-09 22:50:29.941 ERROR 6 --- [           main] o.fluentd.logger.sender.RawSocketSender  : org.fluentd.logger.sender.RawSocketSender

java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.fluentd.logger.sender.RawSocketSender.connect(RawSocketSender.java:83)
	at org.fluentd.logger.sender.RawSocketSender.reconnect(RawSocketSender.java:92)
	at org.fluentd.logger.sender.RawSocketSender.flush(RawSocketSender.java:186)
	at org.fluentd.logger.sender.RawSocketSender.send(RawSocketSender.java:177)
	at org.fluentd.logger.sender.RawSocketSender.emit(RawSocketSender.java:147)
	at org.fluentd.logger.sender.RawSocketSender.emit(RawSocketSender.java:129)
	at org.fluentd.logger.FluentLogger.log(FluentLogger.java:99)
	at ch.qos.logback.more.appenders.DataFluentAppender.append(DataFluentAppender.java:75)
	at ch.qos.logback.more.appenders.DataFluentAppender.append(DataFluentAppender.java:29)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:48)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	at ch.qos.logback.classic.Logger.log(Logger.java:765)
	at org.apache.commons.logging.impl.SLF4JLocationAwareLog.info(SLF4JLocationAwareLog.java:155)
	at org.springframework.boot.StartupInfoLogger.logStarted(StartupInfoLogger.java:57)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
	at net.juniper.pronx.joc.services.Bootstrap.main(Bootstrap.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
...
```

Any help much appreciated.

**Comment by damianoneill** [comment]
fluentd log

```
fluentd_1        | Successfully installed excon-0.54.0
fluentd_1        | Successfully installed multi_json-1.12.1
fluentd_1        | Successfully installed multipart-post-2.0.0
fluentd_1        | Successfully installed faraday-0.10.1
fluentd_1        | Successfully installed elasticsearch-transport-1.0.18
fluentd_1        | Successfully installed elasticsearch-api-1.0.18
fluentd_1        | Successfully installed elasticsearch-1.0.18
fluentd_1        | Successfully installed fluent-plugin-elasticsearch-1.9.2
fluentd_1        | 8 gems installed
fluentd_1        | 2017-01-09 23:17:35 +0000 [info]: reading config file path="/fluentd/etc/fluent.conf"
fluentd_1        | 2017-01-09 23:17:35 +0000 [info]: starting fluentd-0.12.31
fluentd_1        | 2017-01-09 23:17:35 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '1.9.2'
fluentd_1        | 2017-01-09 23:17:35 +0000 [info]: gem 'fluentd' version '0.12.31'
fluentd_1        | 2017-01-09 23:17:35 +0000 [info]: adding match pattern="*.*" type="elasticsearch"
fluentd_1        | 2017-01-09 23:17:36 +0000 [info]: adding source type="forward"
fluentd_1        | 2017-01-09 23:17:36 +0000 [info]: using configuration file: <ROOT>
fluentd_1        |   <source>
fluentd_1        |     type forward
fluentd_1        |     port 24224
fluentd_1        |     bind 0.0.0.0
fluentd_1        |   </source>
fluentd_1        |   <match *.*>
fluentd_1        |     @type elasticsearch
fluentd_1        |     host elasticsearch
fluentd_1        |     logstash_format true
fluentd_1        |     flush_interval 10s
fluentd_1        |   </match>
fluentd_1        | </ROOT>
fluentd_1        | 2017-01-09 23:17:36 +0000 [info]: listening fluent socket on 0.0.0.0:24224
```

Listening Ports on host

```
$ netstat -an | grep 24224
tcp6       0      0  ::1.24224              *.*                    LISTEN
tcp4       0      0  *.24224                *.*                    LISTEN
```

**Comment by damianoneill** [comment]
I just tried with the fluency option

```
            compile 'org.komamitsu:fluency:1.0.0'
            compile 'com.sndyuk:logback-more-appenders:1.4.1'
```


```
<configuration>
    <include resource="org/springframework/boot/logging/logback/base.xml"/>
    <appender name="FLUENCY" class="ch.qos.logback.more.appenders.FluencyLogbackAppender">
        <!-- Tag for Fluentd. Farther information: http://docs.fluentd.org/articles/config-file -->
        <tag>debug</tag>
        <!-- Host name/address and port number which Flentd placed -->
        <remoteHost>127.0.0.1</remoteHost>
        <port>24224</port>
        <layout class="ch.qos.logback.classic.PatternLayout">
            <pattern><![CDATA[%date{HH:mm:ss.SSS} [%thread] %-5level %logger{15}#%line %msg]]></pattern>
        </layout>
    </appender>
    <logger name="net.juniper.pronx.joc" level="debug" additivity="false">
        <appender-ref ref="CONSOLE"/>
        <appender-ref ref="FLUENCY"/>
    </logger>
</configuration>
```

With no success

```
2017-01-10 00:02:21.507  WARN 6 --- [pool-2-thread-1] o.k.fluency.flusher.AsyncFlusher         : ping(): failed, config=Config{host='localhost', port=24224, intervalMillis=1000}
2017-01-10 00:02:21.927  WARN 6 --- [pool-3-thread-1] o.k.fluency.sender.RetryableSender       : Sender failed to send data. sender=RetryableSender{baseSender=MultiSender{senders=[TCPSender{channel=null, config=Config{baseConfig=org.komamitsu.fluency.sender.Sender$Config@28272a62, host='localhost', port=24224, connectionTimeoutMilli=5000, readTimeoutMilli=5000, heartbeaterConfig=Config{baseConfig=Config{host='localhost', port=24224, intervalMillis=1000}}, failureDetectorConfig=Config{failureIntervalMillis=3000}, failureDetectorStrategyConfig=org.komamitsu.fluency.sender.failuredetect.PhiAccrualFailureDetectStrategy$Config@26e0c116}, failureDetector=FailureDetector{failureDetectStrategy=PhiAccrualFailureDetectStrategy{failureDetector=org.komamitsu.failuredetector.PhiAccuralFailureDetector@22df4112} org.komamitsu.fluency.sender.failuredetect.PhiAccrualFailureDetectStrategy@67ddcb2d, heartbeater=TCPHeartbeater{config=Config{baseConfig=Config{host='localhost', port=24224, intervalMillis=1000}}} Heartbeater{config=Config{host='localhost', port=24224, intervalMillis=1000}}, lastFailureTimestampMillis=1484006541507, config=Config{failureIntervalMillis=3000}}} org.komamitsu.fluency.sender.TCPSender@7638898e]} org.komamitsu.fluency.sender.MultiSender@56f00e2e, retryStrategy=ExponentialBackOffRetryStrategy{config=Config{baseConfig=Config{maxRetryCount=7}, baseIntervalMillis=400, maxIntervalMillis=30000}} RetryStrategy{config=Config{maxRetryCount=7}}, isClosed=false} org.komamitsu.fluency.sender.RetryableSender@eff1233, retry=2

org.komamitsu.fluency.sender.MultiSender$AllNodesUnavailableException: All nodes are unavailable
	at org.komamitsu.fluency.sender.MultiSender.sendInternal(MultiSender.java:54)
	at org.komamitsu.fluency.sender.Sender.sendInternalWithRestoreBufferPositions(Sender.java:48)
	at org.komamitsu.fluency.sender.Sender.send(Sender.java:30)
	at org.komamitsu.fluency.sender.RetryableSender.sendInternal(RetryableSender.java:66)
	at org.komamitsu.fluency.sender.Sender.sendInternalWithRestoreBufferPositions(Sender.java:48)
	at org.komamitsu.fluency.sender.Sender.send(Sender.java:30)
	at org.komamitsu.fluency.buffer.PackedForwardBuffer.flushInternal(PackedForwardBuffer.java:230)
	at org.komamitsu.fluency.buffer.Buffer.flush(Buffer.java:81)
	at org.komamitsu.fluency.flusher.AsyncFlusher$1.run(AsyncFlusher.java:31)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Separately, I created a mainline just with Fluency and this worked fine against the EFK stack I'm running. 

```
import org.komamitsu.fluency.Fluency;
import java.util.*;

public class Test {

    public static void main(String args[]) throws Exception {
        Fluency fluency = Fluency.defaultFluency();
        String tag = "foo_db.bar_tbl";
        Map<String, Object> event = new HashMap<String, Object>();
        event.put("name", "komamitsu");
        event.put("age", 42);
        event.put("rate", 3.14);
        fluency.emit(tag, event);

        fluency.close();
    }

}
```

```
{
  "_index": "logstash-2017.01.10",
  "_type": "fluentd",
  "_id": "AVmFra5VsR8zRpUSg86w",
  "_score": null,
  "_source": {
    "rate": 3.14,
    "name": "komamitsu",
    "age": 42,
    "@timestamp": "2017-01-10T00:00:59+00:00"
  },
  "fields": {
    "@timestamp": [
      1484006459000
    ]
  },
  "sort": [
    1484006459000
  ]
}
```

**Comment by damianoneill** [comment]
Non issue, problem with Docker addressing.
