### ISSUE TITLE
ch.qos.logback.more.appenders.DataFluentAppender  Connection closing

### ISSUE THREAD

**Issue by tuxin95** [sndyuk/logback-more-appenders#23]
DataFluentAppender  calls the stop method at startup 
![image](https://user-images.githubusercontent.com/29939855/34705103-d5c4f4c2-f538-11e7-8ae3-a5bf6a574108.png)
![image](https://user-images.githubusercontent.com/29939855/34705107-decdfb36-f538-11e7-8627-4d792ea1eef6.png)
![image](https://user-images.githubusercontent.com/29939855/34705109-e31593f2-f538-11e7-9b77-e04d130a44e3.png)
Sending again would raise the null

**Comment by WilliamTwill** [comment]
I'm having the same issue running Spring-Boot 1.5.10.RELEASE.

`Method threw 'java.lang.NullPointerException' exception. Cannot evaluate org.fluentd.logger.FluentLogger.toString()`
```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at ch.qos.logback.more.appenders.DataFluentAppender.start(DataFluentAppender.java:37)
	  at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)
	  at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	  at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	  at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	  at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	  - locked <0xe5d> (a ch.qos.logback.core.spi.LogbackLock)
	  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	  at org.springframework.boot.logging.logback.LogbackLoggingSystem.configureByResourceUrl(LogbackLoggingSystem.java:173)
	  at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:145)
	  at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:81)
	  at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:59)
	  at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:115)
	  at org.springframework.boot.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:303)
	  at org.springframework.boot.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:276)
	  at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:239)
	  at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:212)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
	  at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74)
	  at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	  at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:325)
	  at org.springframework.boot.SpringApplication.run(SpringApplication.java:296)
	  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	  at my.package.Application.main(Application.java:20)
```

pom.xml
```
        <dependency>
            <groupId>org.fluentd</groupId>
            <artifactId>fluent-logger</artifactId>
            <version>0.3.3</version>
        </dependency>

        <dependency>
            <groupId>com.sndyuk</groupId>
            <artifactId>logback-more-appenders</artifactId>
            <version>1.4.2</version>
        </dependency>
```

Error occurs when spring context is initialized and then reset (second time the `start()` method) is called on the appender.

**Comment by sndyuk** [comment]
@anthofo Thank you for the P/R 👍
